"""Fallback path when no reporting server is configured.

The default install talks to nothing. Rather than making feedback impossible
for those users, a report is rendered as a pre-filled GitHub issue URL that
opens in their browser — they read it, edit it, and submit it themselves.

This has a property the server path does not: the user sees the exact text
before anything is published, and nothing is transmitted by us at all.

Note the URL length limit. GitHub (and browsers) reject very long URLs, so a
report that does not fit is written to a file and the issue body points at
it instead of silently truncating.
"""

from __future__ import annotations

import urllib.parse
import webbrowser
from pathlib import Path
from typing import Any

from sentinel.core.logger import get_logger
from sentinel.feedback.report import Report, ReportKind

log = get_logger(__name__)

#: Conservative ceiling. Browsers vary; 8000 is safe everywhere.
MAX_URL_LENGTH = 8000

#: Issue template file names in .github/ISSUE_TEMPLATE/.
_TEMPLATE_BY_KIND = {
    ReportKind.FALSE_POSITIVE: "false_positive.yml",
    ReportKind.MISSED_DETECTION: "missed_detection.yml",
    ReportKind.BUG: "bug_report.yml",
}

_LABEL_BY_KIND = {
    ReportKind.FALSE_POSITIVE: "false-positive",
    ReportKind.MISSED_DETECTION: "missed-detection",
    ReportKind.BUG: "bug",
}


def build_issue_body(report: Report) -> str:
    """Render a report as GitHub-flavoured markdown."""
    file = report.file
    lines: list[str] = []

    if report.kind is ReportKind.FALSE_POSITIVE:
        lines.append(
            "Sentinel Scan flagged a file I believe is clean.\n"
        )
    elif report.kind is ReportKind.MISSED_DETECTION:
        lines.append(
            "Sentinel Scan did not flag a file I believe is malicious.\n"
        )

    lines.append("### What I expected\n")
    lines.append(report.comment.strip() or "_(not provided)_")
    lines.append("")

    lines.append("### File")
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(f"| Name | `{file.name}` |")
    lines.append(f"| Size | {file.size:,} bytes |")
    lines.append(f"| Type | {file.file_type or 'unknown'} |")
    lines.append(f"| SHA-256 | `{file.sha256}` |")
    if file.md5:
        lines.append(f"| MD5 | `{file.md5}` |")
    if report.origin:
        lines.append(f"| Origin | {report.origin} |")
    lines.append("")

    if report.detections:
        lines.append("### Detections")
        lines.append("")
        lines.append("| Detector | Name | Confidence | Description |")
        lines.append("|---|---|---|---|")
        for detection in report.detections[:15]:
            description = str(detection.get("description", "")).replace("|", "\\|")
            lines.append(
                f"| `{detection.get('detector', '')}` "
                f"| `{detection.get('name', '')}` "
                f"| {detection.get('confidence', 0)} "
                f"| {description[:160]} |"
            )
        if len(report.detections) > 15:
            lines.append("")
            lines.append(f"_…and {len(report.detections) - 15} more._")
        lines.append("")

    lines.append("### Environment")
    lines.append("")
    for key, value in sorted(report.environment.items()):
        lines.append(f"- **{key}**: {value}")
    lines.append("")

    lines.append("---")
    lines.append(
        "<sub>Generated by `sentinel report`. No file contents were included. "
        "Please do not attach malware samples to a public issue — maintainers "
        "will ask for a private channel if a sample is needed.</sub>"
    )

    return "\n".join(lines)


def build_issue_url(report: Report, config: Any) -> str:
    """Build a pre-filled GitHub "new issue" URL for *report*.

    When the body is too long for a URL, it is saved next to the other local
    reports and the URL points the user at that file.
    """
    privacy = getattr(config, "privacy", None)
    repo = str(getattr(privacy, "github_repo", "") or "sentinel-scan/sentinel-scan")

    body = build_issue_body(report)
    title = _title_for(report)

    url = _compose(repo, report, title, body)
    if len(url) <= MAX_URL_LENGTH:
        return url

    # Too long: save the full report and reference it. The comment is
    # truncated here as well — it is frequently what blew the limit, and a
    # "short" body that still embeds it would be no shorter at all.
    from sentinel.feedback.report import save_local

    saved = save_local(report, config)
    comment = report.comment.strip()

    for allowance in (1500, 500, 0):
        excerpt = (
            f"{comment[:allowance]}{'…' if len(comment) > allowance else ''}\n\n"
            if allowance
            else ""
        )
        short_body = (
            f"{excerpt}"
            f"The full report was too long to include in this link. It has "
            f"been saved locally at:\n\n```\n{saved}\n```\n\n"
            f"Please attach that file to this issue. It contains no file "
            f"contents — only hashes, detection names and version "
            f"information.\n\n"
            f"- **SHA-256**: `{report.file.sha256}`\n"
            f"- **File**: `{report.file.name}` ({report.file.size:,} bytes)\n"
        )
        url = _compose(repo, report, title, short_body)
        if len(url) <= MAX_URL_LENGTH:
            return url

    return url


def _compose(repo: str, report: Report, title: str, body: str) -> str:
    params = {
        "title": title,
        "body": body,
        "labels": _LABEL_BY_KIND.get(report.kind, ""),
    }
    template = _TEMPLATE_BY_KIND.get(report.kind)
    if template:
        params["template"] = template

    query = urllib.parse.urlencode(
        {k: v for k, v in params.items() if v}, quote_via=urllib.parse.quote
    )
    return f"https://github.com/{repo}/issues/new?{query}"


def _title_for(report: Report) -> str:
    prefix = {
        ReportKind.FALSE_POSITIVE: "False positive",
        ReportKind.MISSED_DETECTION: "Missed detection",
        ReportKind.BUG: "Bug",
    }[report.kind]

    detail = report.file.name
    if report.detections:
        detail = f"{report.detections[0].get('name', detail)} on {report.file.name}"
    return f"[{prefix}] {detail}"[:200]


def open_in_browser(url: str) -> bool:
    """Open *url* in the user's browser. Returns False if that failed.

    A headless machine or an SSH session has no browser; the caller prints
    the URL instead.
    """
    try:
        return webbrowser.open(url, new=2)
    except Exception as exc:
        log.debug("cannot open a browser: %s", exc)
        return False


def write_issue_file(report: Report, destination: str | Path) -> Path:
    """Write the issue body to a file, for pasting manually."""
    path = Path(destination)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"# {_title_for(report)}\n\n{build_issue_body(report)}\n", encoding="utf-8"
    )
    return path
